services:
  nats:
    container_name: "nats"
    image: nats:2.10.24
    restart: always
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

  chat-server:
    container_name: "chat-server"
    build:
      context: .
      dockerfile: ./build/dockerfile
    volumes:
      - ./server_config.json:/app/server_config.json
    depends_on:
      - nats
    ports:
      - 8080:8080